### PR TITLE
Allow search_key to have multiple segments

### PR DESCRIPTION
**Pull request by rberlind**
I've added code to the datasource that supports processing of multiple segments in search_key.

### CODE REVIEW

**Comment by rberlind** [comment]
@DRuggeri : I noticed that you added query_string parameter to datasource, so added that into my branch for this PR.

**Comment by DRuggeri** [comment]
Hi, @rberlind, thanks for submitting the PR. I apologize for the delay. Unfortunately, this breaks the TestAccRestapiobject_Basic test case:
```
# go test
--- FAIL: TestAccRestapiobject_Basic (2.01s)
        testing.go:518: Step 0 error: Error refreshing: 1 error(s) occurred:

                * data.restapi_object.Foo: 1 error(s) occurred:

                * data.restapi_object.Foo: data.restapi_object.Foo: datasource_api_object.go: The results of parsing 'first' did not return a hash.
FAIL
exit status 1
FAIL    github.com/Mastercard/terraform-provider-restapi/restapi        10.136s
```
I haven't been able to dig into it yet.

**Comment by DRuggeri** [comment]
Hi, @rberlind. I was able to get the nested k/v working fine with a much simpler commit in 5745cb7d4b27b4d7d67de51325668c1bd2221e70.

Please take a look. It's been released as v1.5.0

I've also added a test case that looks for a value an extra level deeper in 4953ba23e4a935192c3099afa57fede9e8b03056.

**Comment by rberlind** [comment]
Hi @DRuggeri 
Apologies on my side for a delayed response.  I have not had time until now to read your comments although I did receive them via email.  It sounds like you were able to incorporate the changes I had made in this PR separately.  I will check out your version and let you know if I think anything else is needed in this connection.
Roger

**Comment by rberlind** [comment]
Your code is definitely a lot simpler. I don't think I thought to invoke GetStringAtKey() instead of GetObjectAtKey().

Unfortunately, when I try using your release 1.5, I end up with an empty id on line 152 of datasource_api_object.go.  I think the reason for this is that line 151 of the same file
`id = fmt.Sprintf("%v", hash[id_attribute])`
is using the original hash passed into GetStringAtKey() instead of a map from inside that hash as is needed. 

In contrast, my code calls GetObjectAtKey() to return the map that includes the target search value and then sets id to `search_hash[id_attribute]`.

Note that my returned matching object starts like this:
```
{
  "data": {
    "id": "ws-Pd5V3FtGng5KTRiT",
    "type": "workspaces",
    "attributes": {
      "name": "gcp-compute-instance",
```
I configured my data source like this:
```
data "restapi_object" "tfe_workspace" {
  path = "/organizations/Cloud-Operations/workspaces"
  id_attribute = "name"
  results_key = "data"
  search_key = "attributes/name"
  search_value = "${var.search_value}"
  debug = true
}
```
(I know it is strange that I am using name as the id instead of id, but this is because the API actually expects name rather than id when I do the HTTP GET at https://app.terraform.io/api/v2/organizations/Cloud-Operations/workspaces/<name>. I did try setting id_attribute to "id" and that allowed id to be set to the id attribute of the workspace I am looking for, ws-Pd5V3FtGng5KTRiT, but then the call done in api_client.go returns a 404 error.)

Having noticed that you now support delimited paths for id_attribute, I also tried setting that to "attributes/name", but that also did not help.  I believe the reason it did not help is that `hash["attributes/name"] is not valid.  

Instead of calling `id = fmt.Sprintf("%v", hash[id_attribute])`, we need to call `id, err = GetStringAtKey(hash, id_attribute, debug)`, although ideally we should add error checking, giving:
```
id, err = GetStringAtKey(hash, id_attribute, debug)
if err != nil {
  return(fmt.Errorf("Failed to find id_attribute '%s' in the record: %s", id_attribute, err))
}
```
After making that change, I was able to get things working.

I looked at your new test case and it makes sense, but I think it only worked because your object id was the default "id" at the top level of the object.  So, your test passed even though the code was not yet fully correct and would not yet handle a nested id.

**Comment by rberlind** [comment]
If you agree that my change and can make it in the master branch, I will be able to close this PR without merging.  Thanks.

**Comment by DRuggeri** [comment]
Hi, @rberlind - thanks for the feedback. Your diagnosis of the issue is exactly correct! I couldn't test that particular use case because of a limitation of `fakeserver`. I've made the code change you suggested in d88d6c70a205d0147acc52dc9606e3ec0e26adcf and released a new `1.5.1` version to fix.

**Comment by rberlind** [comment]
Thanks @DRuggeri I hope to test this weekend.
Roger

**Pull request closed without merging**
