### PR TITLE
Update terraform-plugin-sdk/v2 to pick up grpc max size

### PR DESCRIPTION
**Pull request by artificial-aidan**
Signed-off-by: Aidan Jensen <aidan@artificial.com>

### CODE REVIEW

**Comment by audig** [comment]
I encoutered some issue with the grpc max size
Can I help on this PR ?

**Comment by artificial-aidan** [comment]
https://registry.terraform.io/providers/artificialinc/restapi/latest

**Comment by DRuggeri** [comment]
Thanks for the PR, @artificial-aidan - I'm embarrassed by the slow response. I was in the neighborhood to update dependencies just today so pushed this up to the latest version. I see this has pushed the SDK and grpc dependencies beyond the versions in your PR, so I think we should be good. I'll cut a release shortly for this.

**Comment by artificial-aidan** [comment]
Thanks @DRuggeri !

**Pull request closed without merging**
