### PR TITLE
Add bearer token and create/update method configuration

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Comment by DRuggeri** [comment]
Hi, @yinzara. Thanks for the PR. I have to confess to a mistake I made. Support for changing the HTTP method per activity was actually added in the last release (1.9.0) and committed to master (see #21), but I hadn't pushed these changes up to GitHub yet.

Additionally, the bearer token can already be handled by providing the HTTP header thanks to the `headers` argument documented in `README.md`.

With that in mind, I think the provider can already do what you need. Can you confirm that's the case?

**Comment by yinzara** [comment]
Did not realize that you had added that :) 

The HTTP authorization bearer token header is actually something that I think you should still include.  You can set nearly all of the provider properties via environment variable, however since the headers can't be, you can't set the bearer token via environment variables. This PR adds that capability. You want me to push a change that only has that?

**Comment by DRuggeri** [comment]
I apologize, @yinzara, for the long delay in getting back to you. I was on vacation for a while.

Your use case makes sense, but what do you think about instead adding the ability to set the headers via ENV variable? I prefer that route since it maintains the ability to do most things by ENV.

Something like this could be used:
```
REST_API_HEADER_Authorization=foo
REST_API_HEADER_Bar=baz
```
... and a small function can be used to parse these from the env.

**Comment by ryanhodgson2** [comment]
Hi, are you able to add examples to the example folder that can show the usage of the headers and the format of the hash of strings? Trying to add in a authorization header using a bearer token.

**Comment by gangofnuns** [comment]
> Hi, are you able to add examples to the example folder that can show the usage of the headers and the format of the hash of strings? Trying to add in a authorization header using a bearer token.

I second this.  Not exactly sure how to construct the header.  A mini-doc would help.  Cheers --

**Comment by m-v-k** [comment]
in current version there is oauth authentication support for the provider. It handles the token flows for you.
[See an example here](https://github.com/Mastercard/terraform-provider-restapi/blob/master/examples/provider_with_oauth.tf)

Maybe this pr can be closed?

**Comment by DRuggeri** [comment]
I've gone ahead and added the [example](https://github.com/Mastercard/terraform-provider-restapi/blob/master/examples/provider_with_headers.tf) requested whereby headers can be set arbitrarily outside of terraform and fed in via variables. Thanks, all!

**Pull request closed without merging**
