### PR TITLE
allow to store api data md5hash

### PR DESCRIPTION
**Pull request by fgouteroux**
Hi,

Alow storing md5 hash of api_data instead of all data content.
In some case the payload is big and the tfstate becomes unreadable.
This PR add 2 parameters `data_md5hash` and `update_api_data`. 

Once the resource created, when we need to run TF plan, the resource is read and his state is updated with the response. One more time, in some case the response contains an big payload that we don't want to keep in the tfstate.

Does this is suitable for you ?

### CODE REVIEW

**Comment by DRuggeri** [comment]
Thanks, @fgouteroux for the PR. I don't think as it is implemented would work out well because the `data` attribute contains everything that will be sent and managed by the API client - it's a required parameter.

I think if size and complexity of the state file is an issue, it would be better to add an option to the provider or resource level to omit saving `api_data`. This can be done in [update_state](https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/api_object.go#L171). I guess before returning from the function, an empty map could be constructed to replace `obj.api_data` if the option is set to discard the result.

**Comment by fgouteroux** [comment]
@DRuggeri  yes the`data` attribute contains everything that will be sent and managed by the API client. I don't change this. 

If we declare the parameters `data_md5hash`, we only store the hash of the content in the tfstate.

My use case is to push an new grafana dashboard with the api data json (my payload contain the big dashoard json definition).

I don't want to keep the dashoard json definition in the tfstate.
However, in case of update I have to compare if something change, that is why I choose the md5 hash method. For this I just use the **StateFunc** recommanded by Terraform

https://www.terraform.io/docs/extend/schemas/schema-methods.html
```
// StateFunc is a function called to change the value of this before
// storing it in the state (and likewise before comparing for diffs).
// The use for this is for example with large strings, you may want
// to simply store the hash of it.
Computed  bool
ForceNew  bool
StateFunc SchemaStateFunc
```

### Example of grafana dashboard using data_md5hash

**TF resource definition**

```
resource "restapi_object" "dashboard" {
  path         = "/api/dashboards/db"
  read_path    = "/api/dashboards/uid/{id}"
  update_path  = "/api/dashboards/db"
  update_method = "POST"
  update_api_data = false
  destroy_path = "/api/dashboards/uid/{id}"
  id_attribute = "uid"
  data_md5hash = jsonencode({
    "dashboard": {"title":"My dahsboard","uid":"cQHrs2mGk","version":2,"panels":[{"collapsed":false,"datasource":null,"gridPos":{"h":1,"w":24,"x":0,"y":0},"id":6,"panels":[],"title":"Overview","type":"row"}]}
    "overwrite": var.overwrite
    "folderId": var.folder_id
    "message": "update from terraform"
  })
}
```
**TF plan**
```
+ resource "restapi_object" "dashboard" {
    + api_data        = (known after apply)
    + api_response    = (known after apply)
    + create_response = (known after apply)
    + data_md5hash    = jsonencode(
          {
            + value = "0999c29adf5b8de2f002133f7b097b6e"
          }
      )
    + destroy_path    = "/api/dashboards/uid/{id}"
    + id              = (known after apply)
    + id_attribute    = "uid"
    + path            = "/api/dashboards/db"
    + read_path       = "/api/dashboards/uid/{id}"
    + update_api_data = false
    + update_method   = "POST"
    + update_path     = "/api/dashboards/db"
  }
```

**Comment by DRuggeri** [comment]
OK, thank you for the explanation - that helps quite a bit! I didn't notice the use of `StateFunc` in my initial review.

I would much rather not duplicate the `data` field with a new field serving the same function, but with different side effects. What do you think about maybe just adding a new boolean that controls how we store the state? This could govern both how the StateFunc would work and whether `api_data` and `api_response` are set.

So, we could add a boolean called `brief_state` and...

- Set StateFunc for `data` to be a new function
- If `brief_state` is true, the state function returns a hash and the `set_resource_state` is skipped or a noop
- If `brief_state` is false, the state function returns the string as it is received and `set_resource_state` is implemented as it is today

Does that make sense?

**Comment by DRuggeri** [comment]
Will go ahead and close this one for now since there are conflicts. Would be nice to revisit this likely as part of #81

**Pull request closed without merging**
